### ISSUE TITLE
keystone_manage: action=dbsync is broken on Ocata

### ISSUE THREAD

**Issue by mkhon** [openstack-ansible/openstack-ansible-modules#63]
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_6A7FJu/ansible_module_keystone_manage.py", line 123, in <module>
    main()
  File "/tmp/ansible_6A7FJu/ansible_module_keystone_manage.py", line 109, in main
    changed = will_db_change(conf)
  File "/tmp/ansible_6A7FJu/ansible_module_keystone_manage.py", line 67, in will_db_change
    current_version = migration.get_db_version()
NameError: global name 'migration' is not defined

**Comment by lorin** [comment]
@mkhon This repo isn't actively being maintained anymore, although I'm happy to accept PRs if you'd like to submit a fix.

**Comment by lorin** [comment]
Ah, I see there's a proposed fix at #64.

**Comment by lorin** [comment]
Fixed by #64.

**Comment by mkhon** [comment]
No it is not fixed by #64.

**Comment by lorin** [comment]
Ah, my mistake.
